### ISSUE TITLE
Go-live checklist

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#162]
*A few days before go live*
- [ ] @porta-antiporta Send email to users communicating schedule and expectations for go live
- [ ] @porta-antipotra Configure *Country of Origin* *Void Reasons* in production site

*Day of go live*
9:30 AM 
- [ ] @porta-antiporta Send email to users 1 hr before go live confirming site will go down 
10:30AM 
- [ ] Solomon to disable site or disable all logins to uskpa.org (so data cannot be changed)
- [ ] Solomon to generate .csv dump of legacy uskpa.org site and send files to @Jkrzy 
- [ ] Solomon to redirect `uskpa.org` to new site
- [ ] @Jkrzy to run database migration script for only **initial data** and **licensees** and let @porta-antiporta know when it is done
- [ ] @porta-antiporta to create licensee and auditor accounts and let Solomon know when complete
- [ ] Solomon to double check accounts of licensees and let @Jkrzy know when it checks out
- [ ] @Jkrzy to run database migration script for **certificates** and let Solomon and @porta-antiporta know when it is done
- [ ] @jkrzy Solomon @porta-antiporta perform spot check of new site
~12:00 PM
- [ ] @porta-antiporta to send email to licensees informing them the switch has been completed

*Revert*
Should any critical issues arise during the window that cannot be immediately resolved
- [ ] Solomon to re-enable legacy uskpa.org site
- [ ] Solomon to flip uskpa.org to point back to legacy site
- [ ] @porta-antiporta send out email informing licensees/users/stakeholders

**Comment by porta-antiporta** [comment]
Duplicate of #145
